"""Initial migration

Revision ID: 10aa38b1a164
Revises: 
Create Date: 2024-07-04 18:38:54.962128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10aa38b1a164'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_column('emotional_risk_tolerance_message')
        batch_op.drop_column('financial_resources_message')
        batch_op.drop_column('life_stage_message')
        batch_op.drop_column('risk_category')
        batch_op.drop_column('investment_experience_message')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('risk_category',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=64),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('risk_category',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('investment_experience_message', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('risk_category', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('life_stage_message', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('financial_resources_message', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('emotional_risk_tolerance_message', sa.VARCHAR(length=256), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
