"""Add messages and scores to Profile model

Revision ID: 9f14f08ec6ee
Revises: 10aa38b1a164
Create Date: 2024-07-04 23:03:21.101700

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9f14f08ec6ee'
down_revision = '10aa38b1a164'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('life_stage_message', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('financial_resources_message', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('investment_experience_message', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('emotional_risk_tolerance_message', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('risk_category', sa.String(length=50), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('risk_category',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.drop_column('allocations')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allocations', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.alter_column('risk_category',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)

    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_column('risk_category')
        batch_op.drop_column('emotional_risk_tolerance_message')
        batch_op.drop_column('investment_experience_message')
        batch_op.drop_column('financial_resources_message')
        batch_op.drop_column('life_stage_message')

    # ### end Alembic commands ###
