"""Add risk category to User model

Revision ID: c743cd8ce374
Revises: 3d29906e44f4
Create Date: 2024-07-04 15:35:53.719859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c743cd8ce374'
down_revision = '3d29906e44f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('risk_category', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('risk_category')

    # ### end Alembic commands ###
